name: "dbt_core_EdTech_dataflow"
version: "1.0.0"
profile: dbt_core_EdTech_dataflow
model-paths: ["models"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
